name: Cypress Cloud

on: 
  workflow_dispatch: 
    inputs:
      spec:
        description: Run by cypress command line
        default: cypress/e2e/*
        
jobs:
  cypress-electron-tests: 
    runs-on: ubuntu-latest
    steps: 
      - name: Get code
        uses: actions/checkout@v3.5.3
        
      - name: Cypres run
        uses: cypress-io/github-action@v5.8.2
        with:
          install command: yarn install
          browser: electron
          record: true
          group: UI Electron
          spec: ${{ github.event.inputs.spec }}
        env:
          CYPRESS_RECORD_KEY: d97abe43-87f9-4298-ba8f-23d028522574
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
        
  
        
